apiVersion: v1 
kind: Namespace 
metadata: 
  name:  dpt
--- 
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: fluxdemo 
  namespace: dpt  
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      role: demo 
  template: 
    metadata: 
      labels: 
        role: demo 
    spec: 
      containers: 
      - name: flask 
        image: docker.pkg.github.com/tallmanbrew/docker-package-testing/dpt:latest 
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 80
          name: main
          protocol: TCP
        env: 
        - name: APP_NAME 
          value: dptdemo.K8s.GitOps 
        - name: APP_VERSION 
          value: v1.0.0
      dnsPolicy: ClusterFirst
