apiVersion: v1 
kind: Namespace 
metadata: 
  name:  dpt
--- 
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: flask 
  namespace: dpt  
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      role: demo 
  template: 
    metadata: 
      labels: 
        name: flask
        role: demo 
    spec: 
      containers: 
      - name: flask 
        image: docker.pkg.github.com/tallmanbrew/docker-package-testing/dpt:latest 
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 80
        env: 
        - name: APP_NAME 
          value: dptdemo.K8s.GitOps 
        - name: APP_VERSION 
          value: v1.0.0
      imagePullSecrets:
      - name: github
---
apiVersion: v1
kind: Service
metadata:
  name: flask
  labels:
    name: flask
  namespace: dpt
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: flask
